name: Mise à jour des calendriers
on:
  schedule:
    - cron: '0 4 * * *' # Tous les jours à 4h00 UTC
  workflow_dispatch: # Permet aussi de lancer manuellement avec un bouton

permissions:
  contents: write # Autorise le bot à modifier les fichiers ICS

jobs:
  update-calendars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter les scripts
        env:
          PANDASCORE_TOKEN: ${{ secrets.PANDASCORE_TOKEN }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          python agenda_cs2.py
          python agenda_rl.py
          python agenda.py 

      - name: Sauvegarder les nouveaux ICS sur GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add *.ics
          # S'il n'y a pas de changement, ne fait pas planter le script
          git commit -m "Mise à jour automatique des calendriers" || exit 0
          git push
